# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inv2 <- function(a) {
    .Call('LNAPhyloDyn_inv2', PACKAGE = 'LNAPhyloDyn', a)
}

chols <- function(S) {
    .Call('LNAPhyloDyn_chols', PACKAGE = 'LNAPhyloDyn', S)
}

mvrnormArma <- function(n, sigma) {
    .Call('LNAPhyloDyn_mvrnormArma', PACKAGE = 'LNAPhyloDyn', n, sigma)
}

expM <- function(A) {
    .Call('LNAPhyloDyn_expM', PACKAGE = 'LNAPhyloDyn', A)
}

log_like_traj <- function(SdeTraj, OdeTraj, Filter, gridsize, t_correct = 90) {
    .Call('LNAPhyloDyn_log_like_traj', PACKAGE = 'LNAPhyloDyn', SdeTraj, OdeTraj, Filter, gridsize, t_correct)
}

SIR_log_KOM_Filter2 <- function(OdeTraj, theta1, theta2, gridsize) {
    .Call('LNAPhyloDyn_SIR_log_KOM_Filter2', PACKAGE = 'LNAPhyloDyn', OdeTraj, theta1, theta2, gridsize)
}

SIR_ODE <- function(X, Y, theta1, theta2) {
    .Call('LNAPhyloDyn_SIR_ODE', PACKAGE = 'LNAPhyloDyn', X, Y, theta1, theta2)
}

ODE <- function(initial, t, param) {
    .Call('LNAPhyloDyn_ODE', PACKAGE = 'LNAPhyloDyn', initial, t, param)
}

Traj_sim <- function(initial, OdeTraj, Filter, t_correct = 90) {
    .Call('LNAPhyloDyn_Traj_sim', PACKAGE = 'LNAPhyloDyn', initial, OdeTraj, Filter, t_correct)
}

Traj_sim_ez <- function(initial, times, theta1, theta2, gridsize, t_correct = 90) {
    .Call('LNAPhyloDyn_Traj_sim_ez', PACKAGE = 'LNAPhyloDyn', initial, times, theta1, theta2, gridsize, t_correct)
}

log_like_traj2 <- function(SdeTraj, times, state, theta1, theta2, gridsize, t_correct = 90) {
    .Call('LNAPhyloDyn_log_like_traj2', PACKAGE = 'LNAPhyloDyn', SdeTraj, times, state, theta1, theta2, gridsize, t_correct)
}

coal_loglik <- function(init, f1, t_correct, lambda, gridsize = 1L) {
    .Call('LNAPhyloDyn_coal_loglik', PACKAGE = 'LNAPhyloDyn', init, f1, t_correct, lambda, gridsize)
}

coal_loglik_step <- function(init, f1, t_correct, lambda, gridsize = 1L) {
    .Call('LNAPhyloDyn_coal_loglik_step', PACKAGE = 'LNAPhyloDyn', init, f1, t_correct, lambda, gridsize)
}

ESlice <- function(f_cur, OdeTraj, FTs, state, init, t_correct, lambda = 10, reps = 1L, gridsize = 100L) {
    .Call('LNAPhyloDyn_ESlice', PACKAGE = 'LNAPhyloDyn', f_cur, OdeTraj, FTs, state, init, t_correct, lambda, reps, gridsize)
}

